name: github-docker

on: 
  push: 
    branches:
      - 'docker*'
      - 'master'

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v3
        with:
          build-args: branch_name=${{github.ref_name}}
          context: ./contrib/docker/
          cache-from: type=registry,ref=dealii/dealii:master-focal
          cache-to: type=inline
          push: true
          tags: exadg/exadg:${{github.ref_name}}-focal
